### ISSUE TITLE
Vehicle Status mod 1.10.1 is preventing the match start

### ISSUE THREAD

**Issue by KWJG** [Kurzdor/wotmods-public#1]
I don't know whether this is a problem of version 1.10.1 per se or a wrong interaction with other mod, but Vehicle Status mod version 1.10.1 is preventing the match start.

When the match is loaded and 30 second countdown is started, the game UI is heavily glitched and frozen, denying any further inputs including the Esc menu.

This symptom is not occuring with the previous version (1.9.0). The match normally starts.

I took the python.log with version 1.9.0 (match normally starts) and 1.10.1 (UI freezes and cannot play), and put them into diffchecker site.

Link: [https://www.diffchecker.com/oMEPus1M/](https://www.diffchecker.com/oMEPus1M/)

I hope these logs can help to locate the problem.

**Comment by KWJG** [comment]
Confirmed that the same UI freeze happens even when the Vehicle State mode is the only mod installed.

Here is the log file:

[python-vehiclestate1.10.1-isolated.log](https://github.com/Kurzdor/wotmods-public/files/11071402/python-vehiclestate1.10.1-isolated.log)

**Comment by Kurzdor** [comment]
Thannks for report!
Re-download mod from repository, it was fixed in the same day I got reported from other people. 
Sorry for late response and thanks for really good issue report ;) I really appreciate that.
Closing issue as solved.

Kurzdor

https://github.com/Kurzdor/wotmods-public/releases/tag/VS-1.10.1

**Comment by Kurzdor** [comment]
Oops, I forgot to update mod in Releases section while the one in repository is fixed one.
Sorry about that.
