### ISSUE TITLE
Battle Equipment | Countdown switch bug?

### ISSUE THREAD

**Issue by Project49Music** [Kurzdor/wotmods-public#10]
When I have set the mod to the "Always" it seems to interferre with the ability to switch either the equipment presets and consumables presets at the countdown.
Normally we get the following:
![image](https://github.com/user-attachments/assets/dad19fc0-4b2a-4ffe-8c4f-462d443c015b)

And now it is always this:
![image](https://github.com/user-attachments/assets/34400ed5-e5d7-4d01-be75-283cd0fa7095)
Which is understandable of course when it comes down to the radio button "Always".

Not sure if this is a bug but it feels like this is not supposed to happen this way?

_Closure: I was stupid and messed up some settings not related to the mod._

**Comment by Kurzdor** [comment]
Hey, may I ask what is your screen resolution?

**Comment by Project49Music** [comment]
> Hey, may I ask what is your screen resolution?

Hi Kurzdor, I am using a 1440p monitor. But I found out what my issue was.

I currently have the mark of excellence mod installed by Spoter and it appears that this blocks all notifications inside the garage so basically when I for example turn the ability on or off to switch consumables/equipement I do not get that little notification that it is enabled or disabled.
The only way to tell is to open the notification manager or check the button for a yellow outline, but it doesn't have anything to do with your mod it works perfectly!

I assumed it had something to do with your mod but I was wrong.
