### ISSUE TITLE
When equipment is in battle, such as turbo. It cannot be applied and causes the game to hang. 'Completing the operation'

### ISSUE THREAD

**Issue by Adam1901** [Kurzdor/wotmods-public#3]
The error I'm seeing pretty often is 'Completing the operation' and the game just hangs. Any ideas?

**Comment by captainandrey** [comment]
yup this is the worst bug so far

**Comment by Kurzdor** [comment]
> The error I'm seeing pretty often is 'Completing the operation' and the game just hangs. Any ideas?

Sorry, just saw this
How to reproduce?
Logs?
That might be WG issue.

**Comment by Adam1901** [comment]
I can't consitently reproduce it. But I belive it occours when you have 2 pieces of the same equipment.
one is on a tank in the garage.
one is in a battle.
And when navigating to another tank, it sometimes will hang.

Where does the mod log out to?

**Comment by Kurzdor** [comment]
> Where does the mod log out to?

@Adam1901 As all mods do - send python.log from game folder here.

**Comment by captainandrey** [comment]
[python.log](https://github.com/Kurzdor/wotmods-public/files/11415830/python.log)

Here is mine, I have had the issue 4-5 times yesterday.

**Comment by Kurzdor** [comment]
@captainandrey thanks a lot for helping)

**Comment by Kurzdor** [comment]
@captainandrey please, can you send me your cache file from `%appdata%\Roaming\Wargaming.net\WorldOfTanks\mods\kurzdor\autoequipmentreturn\<YOUR_ACCOUNT_DBID>.dat`?

**Comment by Kurzdor** [comment]
@Adam1901 you should also send me python.log with your error and cache file to help me solve the problem.

**Comment by Kurzdor** [comment]
@captainandrey 
@Adam1901 
Please try this version and send feedback!
https://github.com/Kurzdor/wotmods-public/releases/tag/AER-1.0.2

**Comment by Kurzdor** [comment]
@captainandrey
@Adam1901
Reuploaded version because not finished flash part was in mod package.

**Comment by Adam1901** [comment]
I wiped my install so lost the logs.
I have installed and will report back

**Comment by captainandrey** [comment]
> @captainandrey @Adam1901 Please try this version and send feedback! https://github.com/Kurzdor/wotmods-public/releases/tag/AER-1.0.2

Looking good so far. No crashes with single or 2 available equipment prices.

**Comment by Kurzdor** [comment]
Happy to hear that. Waiting a bit for maybe new feedback and closing the issue.

**Comment by Adam1901** [comment]
Seems to be fixed
Thanks!

Odd question, where do you find the resources to make a mod?

**Comment by Kurzdor** [comment]
@Adam1901 Mostly decompiled WoT code :)
