### ISSUE TITLE
[Auto Equipment Return] How to transfer configuration files when I change my computer.

### ISSUE THREAD

**Issue by monologue112** [Kurzdor/wotmods-public#5]
When I switch to another computer for gaming, I am unable to transfer the previous configuration. Can you please inform me of the storage path for the configuration?

**Comment by Kurzdor** [comment]
It is located in `%appdata%\Roaming\Wargaming.net\WorldOfTanks\mods\kurzdor\autoequipmentreturn`.
You should take file `%accountDBID%.dat` (where `accountDBID` is your id when you look in your WoT profile link there are some number before `-Nickname` - those numbers are your `accountDBID`) and move it to your other PC. 
Or just copy and paste the whole folder.
Sorry for late response.

<details>
<summary>Example on WoT site</summary>
<img src="https://github.com/Kurzdor/wotmods-public/assets/19878951/20eb453f-5a2c-4ccc-b56d-eecc71fd28c3" alt="preview" />
</details>

**Comment by monologue112** [comment]
It's okay, I really appreciate it if you could tell me that.

**Comment by Kurzdor** [comment]
@monologue112 sorry, fixed my comment. Again, it's too late.
