### ISSUE TITLE
Battle Equipment

### ISSUE THREAD

**Issue by Dohtur-Frag** [Kurzdor/wotmods-public#8]
Не знаю, нужно ли это фиксить, но в режиме "Топография" мод работает и показывает пустые слоты.
Может имеет смысл включать отображение если установлено оборудование?

**Comment by Kurzdor** [comment]
@Dohtur-Frag действительно, пропустил. Исправлю в следующем релизе.

**Comment by Kurzdor** [comment]
Исправлено в версии 3.0.2.
