### ISSUE TITLE
Why is the source code for the Auto Equipment Return mod missing?

### ISSUE THREAD

**Issue by War3Evo** [Kurzdor/wotmods-public#9]
Hi [Kurzdor],

I’ve been trying to work with the "Auto Equipment Return" mod and wanted to inspect or modify the source code. However, it seems that only the compiled files are available, and the original Python source code isn’t present in this repository. I’ve tried decompiling the `.pyc` file using tools like **uncompyle6** and **pycdc**, but I encountered errors, such as unsupported opcodes and tuple index errors.

Given that GitHub is primarily an open-source platform, it’s unusual not to include the source code in a public repository. From my understanding, public repositories on GitHub don't necessarily need to be open-source, but without a license specifying the usage terms, legally speaking, the code remains proprietary by default, which limits the community’s ability to contribute, modify, or use the code.

Could you clarify why the source code is missing and whether you intend to keep the project closed-source? If so, it would be helpful to understand the purpose behind this decision. I understand if there are reasons to keep it private, but I wanted to ask because collaboration and transparency are important in the open-source community.

Thanks for your work on the mod, and I appreciate your time in addressing this!

Best regards,  
El Diablo

**Comment by Kurzdor** [comment]
It's closed sourced mod in private repository and I provide compiled downloads of my mods on this repo. That's it.
It's normal practice.
